import usersModule from "./characters";
import displayPeople from "./view";
import "./characters.css";
import "./img/maxresdefault.jpg";

// import "./img/Biggs_Darklighter.png";
// import "./img/luke-skywalker.png";
// import "./img/dark_waider.png";
// import "./img/r2-d2.png";
// import "./img/r5-d4.jpg";
// import "./img/c-3po.png";
// import "./img/chewbacca.png";
// import "./img/greedo.jpg";
// import "./img/Jek_Tono_Porkins.png";
// import "./img/leila organa.png";
// import "./img/Tarkin-SWE.png";
// import "./img/Beru_Lars.jfif";
// import "./img/Han-Solo.png";
// import "./img/jabba-the-hutt-boba-fett-yoda.jpeg";
// import "./img/owen-lars.png";
// import "./img/RaymusAntilles.jpg";
// import "./img/wan-kenobi.png";
// import "./img/Wedge_Antilles.png";
// import "./img/bossk.png";
// import "./img/Character-Lobot.png";
// import "./img/ij-88-jabbapng.png";
// import "./img/lando-calrissian.jpg";
// import "./img/palpatine.png";
// import "./img/yoda.png";
// import "./img/boba-fett.png";
// import "./img/Adi Gallia.png";
// import "./img/ArvelCrynyd.png";
// import "./img/Ayla-Secura.png";
// import "./img/bib_fortuna.png";
// import "./img/ackbar.jpg";
// import "./img/dooku.png";
// import "./img/Eeth_Koth.png";
// import "./img/general-grievous.png";
// import "./img/Ki-Adi-Mundi.png";
// import "./img/Kit_Fisto.jfif";
// import "./img/Luminara-Unduli.png";
// import "./img/mace-windu.png";
// import "./img/Mon_Mothma.png";
// import "./img/nien-nunb.png";
// import "./img/Nute-Gunray.png";
// import "./img/Padmé-Amidala.png";
// import "./img/Plo-Koont.png";
// import "./img/Pogglethelesser_detail.png";
// import "./img/R4-P17-75006.png";
// import "./img/Shaakti_detail.png";
// import "./img/Sly-Moore.png";
// import "./img/tarfful_detail.png";
// import "./img/Tion_Medon.webp";
// import "./img/Anakin-Skywalker.png";
// import "./img/Bail_Organa.png";
// import "./img/Barriss-Offee.png";
// import "./img/cliegglars_detail.png";
// import "./img/Cordé.jpg";
// import "./img/dexterjettster_detail.png";
// import "./img/Dormé.jpg";
// import "./img/Gregar-Typho.png";
// import "./img/Jango Fett.png";
// import "./img/Jar-Jar-Binks.png";
// import "./img/Jocasta-Nu.png";
// import "./img/Lama_su.png";
// import "./img/Saesee-Tiin.png";
// import "./img/San_Hill.png";
// import "./img/Shmi-Skywalker.png";
// import "./img/Taun-We.png";
// import "./img/Wat_Tambor.png";
// import "./img/Watto.png";
// import "./img/Zam_Wesell.png";
// import "./img/Mas_Amedda.png";
// import "./img/BenQuadinarosHS-SWE.png";
// import "./img/Darth-Maul.png";
// import "./img/Dud_Bolt.jpg";
// import "./img/Gasganp.jpg";
// import "./img/Quarsh-Panaka.jpg";
// import "./img/Qui-Gon-Jinn.png";
// import "./img/RattsHS.jpg";
// import "./img/Ric_Olie.jpg";
// import "./img/Roos-Tarpals.png";
// import "./img/RugorNass-SWCT.png";
// import "./img/Sebulba.png";
// import "./img/Valorum-SWE.png";
// import "./img/wicket_w_warwick.png";
// import "./img/Yarael-Poof.png";

const people = `people/?page=`;
const btnInfo = document.getElementById("btn");

export default function () {
  btnInfo.addEventListener("click", () => {
    const peopleId = document.getElementById("filmId").value;
    if (peopleId < 1 || peopleId > 9) return;
    usersModule.getInfo(peopleId, people).then(displayPeople);
  });
}
