const photoCharacters = {
  "https://swapi.dev/api/people/9/": "./img/Biggs_Darklighter.png",
  "https://swapi.dev/api/people/1/": "./img/luke-skywalker.png",
  "https://swapi.dev/api/people/4/": "./img/dark_waider.png",
  "https://swapi.dev/api/people/3/": "./img/r2-d2.png",
  "https://swapi.dev/api/people/8/": "./img/r5-d4.jpg",
  "https://swapi.dev/api/people/2/": "./img/c-3po.png",
  "https://swapi.dev/api/people/13/": "./img/chewbacca.png",
  "https://swapi.dev/api/people/15/": "./img/greedo.jpg",
  "https://swapi.dev/api/people/19/": "./img/Jek_Tono_Porkins.png",
  "https://swapi.dev/api/people/5/": "./img/leila organa.png",
  "https://swapi.dev/api/people/12/": "./img/Tarkin-SWE.png",
  "https://swapi.dev/api/people/7/": "./img/Beru_Lars.jfif",
  "https://swapi.dev/api/people/14/": "./img/Han-Solo.png",
  "https://swapi.dev/api/people/16/":
    "./img/jabba-the-hutt-boba-fett-yoda.jpeg",
  "https://swapi.dev/api/people/6/": "./img/owen-lars.png",
  "https://swapi.dev/api/people/81/": "./img/RaymusAntilles.jpg",
  "https://swapi.dev/api/people/10/": "./img/wan-kenobi.png",
  "https://swapi.dev/api/people/18/": "./img/Wedge_Antilles.png",
  "https://swapi.dev/api/people/24/": "./img/bossk.png",
  "https://swapi.dev/api/people/26/": "./img/Character-Lobot.png",
  "https://swapi.dev/api/people/23/": "./img/ij-88-jabbapng.png",
  "https://swapi.dev/api/people/25/": "./img/lando-calrissian.jpg",
  "https://swapi.dev/api/people/21/": "./img/palpatine.png",
  "https://swapi.dev/api/people/20/": "./img/yoda.png",
  "https://swapi.dev/api/people/22/": "./img/boba-fett.png",
  "https://swapi.dev/api/people/55/": "./img/Adi Gallia.png",
  "https://swapi.dev/api/people/29/": "./img/ArvelCrynyd.png",
  "https://swapi.dev/api/people/46/": "./img/Ayla-Secura.png",
  "https://swapi.dev/api/people/45/": "./img/bib_fortuna.png",
  "https://swapi.dev/api/people/27/": "./img/ackbar.jpg",
  "https://swapi.dev/api/people/67/": "./img/dooku.png",
  "https://swapi.dev/api/people/54/": "./img/Eeth_Koth.png",
  "https://swapi.dev/api/people/79/": "./img/general-grievous.png",
  "https://swapi.dev/api/people/52/": "./img/Ki-Adi-Mundi.png",
  "https://swapi.dev/api/people/53/": "./img/Kit_Fisto.jfif",
  "https://swapi.dev/api/people/64/": "./img/Luminara-Unduli.png",
  "https://swapi.dev/api/people/51/": "./img/mace-windu.png",
  "https://swapi.dev/api/people/28/": "./img/Mon_Mothma.png",
  "https://swapi.dev/api/people/31/": "./img/nien-nunb.png",
  "https://swapi.dev/api/people/33/": "./img/Nute-Gunray.png",
  "https://swapi.dev/api/people/35/": "./img/Padmé-Amidala.png",
  "https://swapi.dev/api/people/58/": "./img/Plo-Koont.png",
  "https://swapi.dev/api/people/63/": "./img/Pogglethelesser_detail.png",
  "https://swapi.dev/api/people/75/": "./img/R4-P17-75006.png",
  "https://swapi.dev/api/people/78/": "./img/Shaakti_detail.png",
  "https://swapi.dev/api/people/82/": "./img/Sly-Moore.png",
  "https://swapi.dev/api/people/80/": "./img/tarfful_detail.png",
  "https://swapi.dev/api/people/83/": "./img/Tion_Medon.webp",
  "https://swapi.dev/api/people/11/": "./img/Anakin-Skywalker.png",
  "https://swapi.dev/api/people/68/": "./img/Bail_Organa.png",
  "https://swapi.dev/api/people/65/": "./img/Barriss-Offee.png",
  "https://swapi.dev/api/people/62/": "./img/cliegglars_detail.png",
  "https://swapi.dev/api/people/61/": "./img/Cordé.jpg",
  "https://swapi.dev/api/people/71/": "./img/dexterjettster_detail.png",
  "https://swapi.dev/api/people/66/": "./img/Dormé.jpg",
  "https://swapi.dev/api/people/60/": "./img/Gregar-Typho.png",
  "https://swapi.dev/api/people/69/": "./img/Jango Fett.png",
  "https://swapi.dev/api/people/36/": "./img/Jar-Jar-Binks.png",
  "https://swapi.dev/api/people/74/": "./img/Jocasta-Nu.png",
  "https://swapi.dev/api/people/72/": "./img/Lama_su.png",
  "https://swapi.dev/api/people/56/": "./img/Saesee-Tiin.png",
  "https://swapi.dev/api/people/77/": "./img/San_Hill.png",
  "https://swapi.dev/api/people/43/": "./img/Shmi-Skywalker.png",
  "https://swapi.dev/api/people/73/": "./img/Taun-We.png",
  "https://swapi.dev/api/people/76/": "./img/Wat_Tambor.png",
  "https://swapi.dev/api/people/40/": "./img/Watto.png",
  "https://swapi.dev/api/people/70/": "./img/Zam_Wesell.png",
  "https://swapi.dev/api/people/59/": "./img/Mas_Amedda.png",
  "https://swapi.dev/api/people/50/": "./img/BenQuadinarosHS-SWE.png",
  "https://swapi.dev/api/people/44/": "./img/Darth-Maul.png",
  "https://swapi.dev/api/people/48/": "./img/Dud_Bolt.jpg",
  "https://swapi.dev/api/people/49/": "./img/Gasganp.jpg",
  "https://swapi.dev/api/people/42/": "./img/Quarsh-Panaka.jpg",
  "https://swapi.dev/api/people/32/": "./img/Qui-Gon-Jinn.png",
  "https://swapi.dev/api/people/47/": "./img/RattsHS.jpg",
  "https://swapi.dev/api/people/39/": "./img/Ric_Olie.jpg",
  "https://swapi.dev/api/people/37/": "./img/Roos-Tarpals.png",
  "https://swapi.dev/api/people/38/": "./img/RugorNass-SWCT.png",
  "https://swapi.dev/api/people/41/": "./img/Sebulba.png",
  "https://swapi.dev/api/people/34/": "./img/Valorum-SWE.png",
  "https://swapi.dev/api/people/30/": "./img/wicket_w_warwick.png",
  "https://swapi.dev/api/people/57/": "./img/Yarael-Poof.png",
};

export default photoCharacters;
